#!//Users/matt/Code/imaging/Paraview/ParaView_release/bin/pvpython

from paraview.simple import *
# load tensor glyphs plugin
paraview.simple._DisableFirstRenderCameraReset()
RenderView1 = CreateRenderView()
RenderView1.LightSpecularColor = [1.0, 1.0, 1.0]
RenderView1.KeyLightAzimuth = 10.0
RenderView1.UseTexturedBackground = 0
RenderView1.UseLight = 1
RenderView1.CameraPosition = [1412.066757286741, 786.9535141158457, 531.1859107668963]
RenderView1.FillLightKFRatio = 3.0
RenderView1.Background2 = [0.0, 0.0, 0.165]
RenderView1.FillLightAzimuth = -10.0
RenderView1.LODResolution = 50.0
RenderView1.BackgroundTexture = []
RenderView1.InteractionMode = '3D'
RenderView1.StencilCapable = 1
RenderView1.LightIntensity = 1.0
RenderView1.CameraFocalPoint = [1516.2000732421875, 1117.2000732421873, 455.00000000000006]
RenderView1.ImageReductionFactor = 2
RenderView1.CameraViewAngle = 30.0
RenderView1.CameraParallelScale = 1937.5303006022807
RenderView1.EyeAngle = 2.0
RenderView1.HeadLightKHRatio = 3.0
RenderView1.StereoRender = 0
RenderView1.KeyLightIntensity = 0.75
RenderView1.BackLightAzimuth = 110.0
RenderView1.OrientationAxesInteractivity = 0
RenderView1.UseInteractiveRenderingForSceenshots = 0
RenderView1.UseOffscreenRendering = 0
RenderView1.Background = [0.31999694819562063, 0.3400015259021897, 0.4299992370489052]
RenderView1.UseOffscreenRenderingForScreenshots = 0
RenderView1.NonInteractiveRenderDelay = 2
RenderView1.CenterOfRotation = [1516.2000732421875, 1117.2000732421875, 455.0]
RenderView1.CameraParallelProjection = 0
RenderView1.CompressorConfig = 'vtkSquirtCompressor 0 3'
RenderView1.HeadLightWarmth = 0.5
RenderView1.MaximumNumberOfPeels = 4
RenderView1.LightDiffuseColor = [1.0, 1.0, 1.0]
RenderView1.StereoType = 'Red-Blue'
RenderView1.DepthPeeling = 1
RenderView1.BackLightKBRatio = 3.5
RenderView1.StereoCapableWindow = 1
RenderView1.CameraViewUp = [0.057209234012172934, 0.20725931323939822, 0.9766118372307769]
RenderView1.LightType = 'HeadLight'
RenderView1.LightAmbientColor = [1.0, 1.0, 1.0]
RenderView1.RemoteRenderThreshold = 3.0
RenderView1.CacheKey = 0.0
RenderView1.UseCache = 0
RenderView1.KeyLightElevation = 50.0
RenderView1.CenterAxesVisibility = 1
RenderView1.MaintainLuminance = 0
RenderView1.StillRenderImageReductionFactor = 1
RenderView1.BackLightWarmth = 0.5
RenderView1.FillLightElevation = -75.0
RenderView1.MultiSamples = 0
RenderView1.FillLightWarmth = 0.4
RenderView1.AlphaBitPlanes = 1
RenderView1.LightSwitch = 0
RenderView1.OrientationAxesVisibility = 1
RenderView1.CameraClippingRange = [3.4137408738059993, 3413.7408738059994]
RenderView1.BackLightElevation = 0.0
RenderView1.ViewTime = 0.0
RenderView1.OrientationAxesOutlineColor = [1.0, 1.0, 1.0]
RenderView1.LODThreshold = 5.0
RenderView1.CollectGeometryThreshold = 100.0
RenderView1.UseGradientBackground = 0
RenderView1.KeyLightWarmth = 0.6
RenderView1.OrientationAxesLabelColor = [1.0, 1.0, 1.0]
RenderView1.ViewSize = [2000, 2000] #[width, height]
HiRes_ST_vtk = LegacyVTKReader( guiName="HiRes_ST.vtk", FileNames=['/Users/matt/Code/imaging/registration/results/Rat28/bottom_vessels/HiResPairs/AdjustedTransforms/CenteredAffineTransform_20/downsamples_1_16/HiRes_ST.vtk'] )
HiRes_mha = MetaFileSeriesReader( guiName="HiRes.mha", FileNames=['/Users/matt/Code/imaging/registration/results/Rat28/bottom_vessels/HiResPairs/AdjustedTransforms/CenteredAffineTransform_20/downsamples_1_16/HiRes.mha'] )
SetActiveSource(HiRes_ST_vtk)
ExtractSubset1 = ExtractSubset( guiName="ExtractSubset1", IncludeBoundary=0, VOI=[0, 114, 0, 84, 45, 45], SampleRateK=1, SampleRateJ=1, SampleRateI=1 )
SetActiveSource(HiRes_mha)
ExtractSubset2 = ExtractSubset( guiName="ExtractSubset2", IncludeBoundary=0, VOI=[0, 114, 0, 84, 44, 46], SampleRateK=1, SampleRateJ=1, SampleRateI=1 )
Slice1 = Slice( guiName="Slice1", SliceOffsetValues=[0.0], SliceType="Plane" )
Slice1.SliceType.Offset = 0.0
Slice1.SliceType.Origin = [1516.20002174377, 1117.20001602173, 450.0]
Slice1.SliceType.Normal = [0.0, 0.0, 1.0]
SetActiveSource(ExtractSubset1)
TensorGlyphs1 = TensorGlyphs( guiName="TensorGlyphs1", GlyphType="Sphere", Scalars=['POINTS', ''], LimitScalingByEigenvalues=0, ColorGlyphs=1, Symmetric=0, Colorby='input scalars', MaxScaleFactor=10.0, ThreeGlyphs=1, ExtractEigenvalues=1, ScaleFactor=1.0, Tensors=['POINTS', 'tensors'] )
TensorGlyphs1.GlyphType.Center = [0.0, 0.0, 0.0]
TensorGlyphs1.GlyphType.ThetaResolution = 16
TensorGlyphs1.GlyphType.EndPhi = 180.0
TensorGlyphs1.GlyphType.Radius = 5
TensorGlyphs1.GlyphType.PhiResolution = 32
TensorGlyphs1.GlyphType.EndTheta = 360
TensorGlyphs1.GlyphType.StartTheta = 0.0
TensorGlyphs1.GlyphType.StartPhi = 0.0
a9_tensors_PiecewiseFunction = CreatePiecewiseFunction( Points=[0.0, 0.0, 0.5, 0.0, 1.0, 1.0, 0.5, 0.0] )
a3_MetaImage_PiecewiseFunction = CreatePiecewiseFunction( Points=[0.0, 0.0, 0.5, 0.0, 1.0, 1.0, 0.5, 0.0] )
a9_tensors_PVLookupTable = GetLookupTableForArray( "tensors", 9, Discretize=1, RGBPoints=[0.0, 0.23, 0.299, 0.754, 46.17102359917577, 0.706, 0.016, 0.15], UseLogScale=0, VectorComponent=0, NanColor=[0.25, 0.0, 0.0], NumberOfTableValues=256, ColorSpace='Diverging', VectorMode='Magnitude', HSVWrap=0, ScalarRangeInitialized=1.0, LockScalarRange=0 )
a3_MetaImage_PVLookupTable = GetLookupTableForArray( "MetaImage", 3, Discretize=1, RGBPoints=[230.39748262513635, 0.23, 0.299, 0.754, 441.6729559300637, 0.706, 0.016, 0.15], UseLogScale=0, VectorComponent=0, NanColor=[0.25, 0.0, 0.0], NumberOfTableValues=256, ColorSpace='Diverging', VectorMode='Magnitude', HSVWrap=0, ScalarRangeInitialized=1.0, LockScalarRange=0 )
SetActiveSource(HiRes_ST_vtk)
DataRepresentation1 = Show()
DataRepresentation1.CubeAxesZAxisVisibility = 1
DataRepresentation1.SelectionPointLabelColor = [0.5, 0.5, 0.5]
DataRepresentation1.SelectionPointFieldDataArrayName = 'tensors'
DataRepresentation1.SuppressLOD = 0
DataRepresentation1.CubeAxesXGridLines = 0
DataRepresentation1.CubeAxesYAxisTickVisibility = 1
DataRepresentation1.CubeAxesColor = [1.0, 1.0, 1.0]
DataRepresentation1.Position = [0.0, 0.0, 0.0]
DataRepresentation1.BackfaceRepresentation = 'Follow Frontface'
DataRepresentation1.SelectionOpacity = 1.0
DataRepresentation1.SelectionPointLabelShadow = 0
DataRepresentation1.CubeAxesYGridLines = 0
DataRepresentation1.CubeAxesZAxisRange = [0.0, 1.0]
DataRepresentation1.OrientationMode = 'Direction'
DataRepresentation1.Source.TipResolution = 6
DataRepresentation1.ScaleMode = 'No Data Scaling Off'
DataRepresentation1.Diffuse = 1.0
DataRepresentation1.SelectionUseOutline = 0
DataRepresentation1.CubeAxesZTitle = 'Z-Axis'
DataRepresentation1.Specular = 0.1
DataRepresentation1.SelectionVisibility = 1
DataRepresentation1.InterpolateScalarsBeforeMapping = 1
DataRepresentation1.CubeAxesZAxisTickVisibility = 1
DataRepresentation1.Origin = [0.0, 0.0, 0.0]
DataRepresentation1.CubeAxesVisibility = 0
DataRepresentation1.Scale = [1.0, 1.0, 1.0]
DataRepresentation1.SelectionCellLabelJustification = 'Left'
DataRepresentation1.DiffuseColor = [1.0, 1.0, 1.0]
DataRepresentation1.Shade = 0
DataRepresentation1.SelectionCellLabelOpacity = 1.0
DataRepresentation1.CubeAxesInertia = 1
DataRepresentation1.Source = "Arrow"
DataRepresentation1.Source.Invert = 0
DataRepresentation1.Masking = 0
DataRepresentation1.Opacity = 1.0
DataRepresentation1.LineWidth = 1.0
DataRepresentation1.MeshVisibility = 0
DataRepresentation1.Visibility = 1
DataRepresentation1.SelectionCellLabelFontSize = 18
DataRepresentation1.CubeAxesCornerOffset = 0.0
DataRepresentation1.SelectionPointLabelJustification = 'Left'
DataRepresentation1.SelectionPointLabelVisibility = 0
DataRepresentation1.SelectOrientationVectors = ''
DataRepresentation1.CubeAxesTickLocation = 'Inside'
DataRepresentation1.BackfaceDiffuseColor = [1.0, 1.0, 1.0]
DataRepresentation1.CubeAxesYAxisVisibility = 1
DataRepresentation1.SelectionPointLabelFontFamily = 'Arial'
DataRepresentation1.Source.ShaftResolution = 6
DataRepresentation1.CubeAxesFlyMode = 'Closest Triad'
DataRepresentation1.SelectScaleArray = ''
DataRepresentation1.CubeAxesYTitle = 'Y-Axis'
DataRepresentation1.ColorAttributeType = 'POINT_DATA'
DataRepresentation1.SpecularPower = 100.0
DataRepresentation1.Texture = []
DataRepresentation1.SelectionCellLabelShadow = 0
DataRepresentation1.AmbientColor = [1.0, 1.0, 1.0]
DataRepresentation1.MapScalars = 1
DataRepresentation1.PointSize = 2.0
DataRepresentation1.Source.TipLength = 0.35
DataRepresentation1.SelectionCellLabelFormat = ''
DataRepresentation1.Scaling = 0
DataRepresentation1.StaticMode = 0
DataRepresentation1.SelectionCellLabelColor = [0.0, 1.0, 0.0]
DataRepresentation1.SliceMode = 'XY Plane'
DataRepresentation1.Source.TipRadius = 0.1
DataRepresentation1.EdgeColor = [0.0, 0.0, 0.5000076295109483]
DataRepresentation1.CubeAxesXAxisTickVisibility = 1
DataRepresentation1.SelectionCellLabelVisibility = 0
DataRepresentation1.NonlinearSubdivisionLevel = 1
DataRepresentation1.CubeAxesXAxisRange = [0.0, 1.0]
DataRepresentation1.Representation = 'Outline'
DataRepresentation1.CubeAxesYAxisRange = [0.0, 1.0]
DataRepresentation1.CustomBounds = [0.0, 1.0, 0.0, 1.0, 0.0, 1.0]
DataRepresentation1.Orientation = [0.0, 0.0, 0.0]
DataRepresentation1.CubeAxesEnableCustomAxisRange = 0
DataRepresentation1.CubeAxesXTitle = 'X-Axis'
DataRepresentation1.ScalarOpacityUnitDistance = 40.569841008675475
DataRepresentation1.BackfaceOpacity = 1.0
DataRepresentation1.SelectionPointLabelFontSize = 18
DataRepresentation1.SelectionCellFieldDataArrayName = 'vtkOriginalCellIds'
DataRepresentation1.SelectionColor = [1.0, 0.0, 1.0]
DataRepresentation1.Ambient = 0.0
DataRepresentation1.VolumeRenderingMode = 'Smart'
DataRepresentation1.CubeAxesXAxisMinorTickVisibility = 1
DataRepresentation1.ScaleFactor = 303.2400043487549
DataRepresentation1.BackfaceAmbientColor = [1.0, 1.0, 1.0]
DataRepresentation1.Slice = 0
DataRepresentation1.Source.ShaftRadius = 0.03
DataRepresentation1.ScalarOpacityFunction = []
DataRepresentation1.SelectMaskArray = ''
DataRepresentation1.SelectionLineWidth = 2.0
DataRepresentation1.CubeAxesZAxisMinorTickVisibility = 1
DataRepresentation1.CubeAxesXAxisVisibility = 1
DataRepresentation1.Interpolation = 'Gouraud'
DataRepresentation1.SelectionCellLabelFontFamily = 'Arial'
DataRepresentation1.SelectionCellLabelItalic = 0
DataRepresentation1.CubeAxesYAxisMinorTickVisibility = 1
DataRepresentation1.InterpolationType = 'Linear'
DataRepresentation1.CubeAxesZGridLines = 0
DataRepresentation1.SelectionPointLabelFormat = ''
DataRepresentation1.SelectionPointLabelOpacity = 1.0
DataRepresentation1.Pickable = 1
DataRepresentation1.CustomBoundsActive = [0, 0, 0]
DataRepresentation1.SelectionRepresentation = 'Wireframe'
DataRepresentation1.SelectionPointLabelBold = 0
DataRepresentation1.ColorArrayName = ''
DataRepresentation1.SelectionPointLabelItalic = 0
DataRepresentation1.AllowSpecularHighlightingWithScalarColoring = 0
DataRepresentation1.SpecularColor = [1.0, 1.0, 1.0]
DataRepresentation1.LookupTable = []
DataRepresentation1.SelectionPointSize = 5.0
DataRepresentation1.SelectionCellLabelBold = 0
DataRepresentation1.Orient = 0
SetActiveSource(HiRes_mha)
DataRepresentation2 = Show()
DataRepresentation2.CubeAxesZAxisVisibility = 1
DataRepresentation2.SelectionPointLabelColor = [0.5, 0.5, 0.5]
DataRepresentation2.SelectionPointFieldDataArrayName = 'MetaImage'
DataRepresentation2.SuppressLOD = 0
DataRepresentation2.CubeAxesXGridLines = 0
DataRepresentation2.CubeAxesYAxisTickVisibility = 1
DataRepresentation2.CubeAxesColor = [1.0, 1.0, 1.0]
DataRepresentation2.Position = [0.0, 0.0, 0.0]
DataRepresentation2.BackfaceRepresentation = 'Follow Frontface'
DataRepresentation2.SelectionOpacity = 1.0
DataRepresentation2.SelectionPointLabelShadow = 0
DataRepresentation2.CubeAxesYGridLines = 0
DataRepresentation2.CubeAxesZAxisRange = [0.0, 1.0]
DataRepresentation2.OrientationMode = 'Direction'
DataRepresentation2.Source.TipResolution = 6
DataRepresentation2.ScaleMode = 'No Data Scaling Off'
DataRepresentation2.Diffuse = 1.0
DataRepresentation2.SelectionUseOutline = 0
DataRepresentation2.CubeAxesZTitle = 'Z-Axis'
DataRepresentation2.Specular = 0.1
DataRepresentation2.SelectionVisibility = 1
DataRepresentation2.InterpolateScalarsBeforeMapping = 1
DataRepresentation2.CubeAxesZAxisTickVisibility = 1
DataRepresentation2.Origin = [0.0, 0.0, 0.0]
DataRepresentation2.CubeAxesVisibility = 0
DataRepresentation2.Scale = [1.0, 1.0, 1.0]
DataRepresentation2.SelectionCellLabelJustification = 'Left'
DataRepresentation2.DiffuseColor = [1.0, 1.0, 1.0]
DataRepresentation2.Shade = 0
DataRepresentation2.SelectionCellLabelOpacity = 1.0
DataRepresentation2.CubeAxesInertia = 1
DataRepresentation2.Source = "Arrow"
DataRepresentation2.Source.Invert = 0
DataRepresentation2.Masking = 0
DataRepresentation2.Opacity = 1.0
DataRepresentation2.LineWidth = 1.0
DataRepresentation2.MeshVisibility = 0
DataRepresentation2.Visibility = 1
DataRepresentation2.SelectionCellLabelFontSize = 18
DataRepresentation2.CubeAxesCornerOffset = 0.0
DataRepresentation2.SelectionPointLabelJustification = 'Left'
DataRepresentation2.SelectionPointLabelVisibility = 0
DataRepresentation2.SelectOrientationVectors = ''
DataRepresentation2.CubeAxesTickLocation = 'Inside'
DataRepresentation2.BackfaceDiffuseColor = [1.0, 1.0, 1.0]
DataRepresentation2.CubeAxesYAxisVisibility = 1
DataRepresentation2.SelectionPointLabelFontFamily = 'Arial'
DataRepresentation2.Source.ShaftResolution = 6
DataRepresentation2.CubeAxesFlyMode = 'Closest Triad'
DataRepresentation2.SelectScaleArray = ''
DataRepresentation2.CubeAxesYTitle = 'Y-Axis'
DataRepresentation2.ColorAttributeType = 'POINT_DATA'
DataRepresentation2.SpecularPower = 100.0
DataRepresentation2.Texture = []
DataRepresentation2.SelectionCellLabelShadow = 0
DataRepresentation2.AmbientColor = [1.0, 1.0, 1.0]
DataRepresentation2.MapScalars = 1
DataRepresentation2.PointSize = 2.0
DataRepresentation2.Source.TipLength = 0.35
DataRepresentation2.SelectionCellLabelFormat = ''
DataRepresentation2.Scaling = 0
DataRepresentation2.StaticMode = 0
DataRepresentation2.SelectionCellLabelColor = [0.0, 1.0, 0.0]
DataRepresentation2.SliceMode = 'XY Plane'
DataRepresentation2.Source.TipRadius = 0.1
DataRepresentation2.EdgeColor = [0.0, 0.0, 0.5000076295109483]
DataRepresentation2.CubeAxesXAxisTickVisibility = 1
DataRepresentation2.SelectionCellLabelVisibility = 0
DataRepresentation2.NonlinearSubdivisionLevel = 1
DataRepresentation2.CubeAxesXAxisRange = [0.0, 1.0]
DataRepresentation2.Representation = 'Outline'
DataRepresentation2.CubeAxesYAxisRange = [0.0, 1.0]
DataRepresentation2.CustomBounds = [0.0, 1.0, 0.0, 1.0, 0.0, 1.0]
DataRepresentation2.Orientation = [0.0, 0.0, 0.0]
DataRepresentation2.CubeAxesEnableCustomAxisRange = 0
DataRepresentation2.CubeAxesXTitle = 'X-Axis'
DataRepresentation2.ScalarOpacityUnitDistance = 40.569841008675475
DataRepresentation2.BackfaceOpacity = 1.0
DataRepresentation2.SelectionPointLabelFontSize = 18
DataRepresentation2.SelectionCellFieldDataArrayName = 'vtkOriginalCellIds'
DataRepresentation2.SelectionColor = [1.0, 0.0, 1.0]
DataRepresentation2.Ambient = 0.0
DataRepresentation2.VolumeRenderingMode = 'Smart'
DataRepresentation2.CubeAxesXAxisMinorTickVisibility = 1
DataRepresentation2.ScaleFactor = 303.2400043487549
DataRepresentation2.BackfaceAmbientColor = [1.0, 1.0, 1.0]
DataRepresentation2.Slice = 0
DataRepresentation2.Source.ShaftRadius = 0.03
DataRepresentation2.ScalarOpacityFunction = []
DataRepresentation2.SelectMaskArray = ''
DataRepresentation2.SelectionLineWidth = 2.0
DataRepresentation2.CubeAxesZAxisMinorTickVisibility = 1
DataRepresentation2.CubeAxesXAxisVisibility = 1
DataRepresentation2.Interpolation = 'Gouraud'
DataRepresentation2.SelectionCellLabelFontFamily = 'Arial'
DataRepresentation2.SelectionCellLabelItalic = 0
DataRepresentation2.CubeAxesYAxisMinorTickVisibility = 1
DataRepresentation2.InterpolationType = 'Linear'
DataRepresentation2.CubeAxesZGridLines = 0
DataRepresentation2.SelectionPointLabelFormat = ''
DataRepresentation2.SelectionPointLabelOpacity = 1.0
DataRepresentation2.Pickable = 1
DataRepresentation2.CustomBoundsActive = [0, 0, 0]
DataRepresentation2.SelectionRepresentation = 'Wireframe'
DataRepresentation2.SelectionPointLabelBold = 0
DataRepresentation2.ColorArrayName = ''
DataRepresentation2.SelectionPointLabelItalic = 0
DataRepresentation2.AllowSpecularHighlightingWithScalarColoring = 0
DataRepresentation2.SpecularColor = [1.0, 1.0, 1.0]
DataRepresentation2.LookupTable = []
DataRepresentation2.SelectionPointSize = 5.0
DataRepresentation2.SelectionCellLabelBold = 0
DataRepresentation2.Orient = 0
SetActiveSource(TensorGlyphs1)
DataRepresentation6 = Show()
DataRepresentation6.CubeAxesZAxisVisibility = 1
DataRepresentation6.SelectionPointLabelColor = [0.5, 0.5, 0.5]
DataRepresentation6.SelectionPointFieldDataArrayName = 'Normals'
DataRepresentation6.SuppressLOD = 0
DataRepresentation6.CubeAxesXGridLines = 0
DataRepresentation6.CubeAxesYAxisTickVisibility = 1
DataRepresentation6.CubeAxesColor = [1.0, 1.0, 1.0]
DataRepresentation6.Position = [0.0, 0.0, 0.0]
DataRepresentation6.BackfaceRepresentation = 'Follow Frontface'
DataRepresentation6.SelectionOpacity = 1.0
DataRepresentation6.SelectionPointLabelShadow = 0
DataRepresentation6.CubeAxesYGridLines = 0
DataRepresentation6.CubeAxesZAxisRange = [0.0, 1.0]
DataRepresentation6.OrientationMode = 'Direction'
DataRepresentation6.Source.TipResolution = 6
DataRepresentation6.ScaleMode = 'No Data Scaling Off'
DataRepresentation6.Diffuse = 1.0
DataRepresentation6.SelectionUseOutline = 0
DataRepresentation6.CubeAxesZTitle = 'Z-Axis'
DataRepresentation6.Specular = 0.1
DataRepresentation6.SelectionVisibility = 1
DataRepresentation6.InterpolateScalarsBeforeMapping = 1
DataRepresentation6.CubeAxesZAxisTickVisibility = 1
DataRepresentation6.Origin = [0.0, 0.0, 0.0]
DataRepresentation6.CubeAxesVisibility = 0
DataRepresentation6.Scale = [1.0, 1.0, 1.0]
DataRepresentation6.SelectionCellLabelJustification = 'Left'
DataRepresentation6.DiffuseColor = [1.0, 1.0, 1.0]
DataRepresentation6.SelectionCellLabelOpacity = 1.0
DataRepresentation6.Source = "Arrow"
DataRepresentation6.Source.Invert = 0
DataRepresentation6.Masking = 0
DataRepresentation6.Opacity = 1.0
DataRepresentation6.LineWidth = 1.0
DataRepresentation6.MeshVisibility = 0
DataRepresentation6.Visibility = 1
DataRepresentation6.SelectionCellLabelFontSize = 18
DataRepresentation6.CubeAxesCornerOffset = 0.0
DataRepresentation6.SelectionPointLabelJustification = 'Left'
DataRepresentation6.SelectionPointLabelVisibility = 0
DataRepresentation6.SelectOrientationVectors = ''
DataRepresentation6.CubeAxesTickLocation = 'Inside'
DataRepresentation6.CubeAxesXAxisMinorTickVisibility = 1
DataRepresentation6.CubeAxesYAxisVisibility = 1
DataRepresentation6.SelectionPointLabelFontFamily = 'Arial'
DataRepresentation6.Source.ShaftResolution = 6
DataRepresentation6.CubeAxesFlyMode = 'Closest Triad'
DataRepresentation6.SelectScaleArray = ''
DataRepresentation6.CubeAxesYTitle = 'Y-Axis'
DataRepresentation6.ColorAttributeType = 'POINT_DATA'
DataRepresentation6.SpecularPower = 100.0
DataRepresentation6.Texture = []
DataRepresentation6.SelectionCellLabelShadow = 0
DataRepresentation6.AmbientColor = [1.0, 1.0, 1.0]
DataRepresentation6.MapScalars = 1
DataRepresentation6.PointSize = 2.0
DataRepresentation6.Source.TipLength = 0.35
DataRepresentation6.SelectionCellLabelFormat = ''
DataRepresentation6.Scaling = 0
DataRepresentation6.StaticMode = 0
DataRepresentation6.SelectionCellLabelColor = [0.0, 1.0, 0.0]
DataRepresentation6.Source.TipRadius = 0.1
DataRepresentation6.EdgeColor = [0.0, 0.0, 0.5000076295109483]
DataRepresentation6.CubeAxesXAxisTickVisibility = 1
DataRepresentation6.SelectionCellLabelVisibility = 0
DataRepresentation6.NonlinearSubdivisionLevel = 1
DataRepresentation6.CubeAxesXAxisRange = [0.0, 1.0]
DataRepresentation6.Representation = 'Surface'
DataRepresentation6.CubeAxesYAxisRange = [0.0, 1.0]
DataRepresentation6.CustomBounds = [0.0, 1.0, 0.0, 1.0, 0.0, 1.0]
DataRepresentation6.Orientation = [0.0, 0.0, 0.0]
DataRepresentation6.CubeAxesEnableCustomAxisRange = 0
DataRepresentation6.CubeAxesXTitle = 'X-Axis'
DataRepresentation6.CubeAxesInertia = 1
DataRepresentation6.BackfaceOpacity = 1.0
DataRepresentation6.SelectionCellFieldDataArrayName = 'vtkOriginalCellIds'
DataRepresentation6.SelectionColor = [1.0, 0.0, 1.0]
DataRepresentation6.Ambient = 0.0
DataRepresentation6.SelectionPointLabelFontSize = 18
DataRepresentation6.ScaleFactor = 303.40051274384257
DataRepresentation6.BackfaceAmbientColor = [1.0, 1.0, 1.0]
DataRepresentation6.Source.ShaftRadius = 0.03
DataRepresentation6.SelectMaskArray = ''
DataRepresentation6.SelectionLineWidth = 2.0
DataRepresentation6.CubeAxesZAxisMinorTickVisibility = 1
DataRepresentation6.CubeAxesXAxisVisibility = 1
DataRepresentation6.Interpolation = 'Gouraud'
DataRepresentation6.SelectionCellLabelFontFamily = 'Arial'
DataRepresentation6.SelectionCellLabelItalic = 0
DataRepresentation6.CubeAxesYAxisMinorTickVisibility = 1
DataRepresentation6.CubeAxesZGridLines = 0
DataRepresentation6.SelectionPointLabelFormat = ''
DataRepresentation6.SelectionPointLabelOpacity = 1.0
DataRepresentation6.BackfaceDiffuseColor = [1.0, 1.0, 1.0]
DataRepresentation6.Pickable = 1
DataRepresentation6.CustomBoundsActive = [0, 0, 0]
DataRepresentation6.SelectionRepresentation = 'Wireframe'
DataRepresentation6.SelectionPointLabelBold = 0
DataRepresentation6.ColorArrayName = ''
DataRepresentation6.SelectionPointLabelItalic = 0
DataRepresentation6.AllowSpecularHighlightingWithScalarColoring = 0
DataRepresentation6.SpecularColor = [1.0, 1.0, 1.0]
DataRepresentation6.LookupTable = []
DataRepresentation6.SelectionPointSize = 5.0
DataRepresentation6.SelectionCellLabelBold = 0
DataRepresentation6.Orient = 0
SetActiveSource(Slice1)
DataRepresentation5 = Show()
DataRepresentation5.CubeAxesZAxisVisibility = 1
DataRepresentation5.SelectionPointLabelColor = [0.5, 0.5, 0.5]
DataRepresentation5.SelectionPointFieldDataArrayName = 'MetaImage'
DataRepresentation5.SuppressLOD = 0
DataRepresentation5.CubeAxesXGridLines = 0
DataRepresentation5.CubeAxesYAxisTickVisibility = 1
DataRepresentation5.CubeAxesColor = [1.0, 1.0, 1.0]
DataRepresentation5.Position = [0.0, 0.0, 0.0]
DataRepresentation5.BackfaceRepresentation = 'Follow Frontface'
DataRepresentation5.SelectionOpacity = 1.0
DataRepresentation5.SelectionPointLabelShadow = 0
DataRepresentation5.CubeAxesYGridLines = 0
DataRepresentation5.CubeAxesZAxisRange = [0.0, 1.0]
DataRepresentation5.OrientationMode = 'Direction'
DataRepresentation5.Source.TipResolution = 6
DataRepresentation5.ScaleMode = 'No Data Scaling Off'
DataRepresentation5.Diffuse = 1.0
DataRepresentation5.SelectionUseOutline = 0
DataRepresentation5.CubeAxesZTitle = 'Z-Axis'
DataRepresentation5.Specular = 0.1
DataRepresentation5.SelectionVisibility = 1
DataRepresentation5.InterpolateScalarsBeforeMapping = 1
DataRepresentation5.CubeAxesZAxisTickVisibility = 1
DataRepresentation5.Origin = [0.0, 0.0, 0.0]
DataRepresentation5.CubeAxesVisibility = 0
DataRepresentation5.Scale = [1.0, 1.0, 1.0]
DataRepresentation5.SelectionCellLabelJustification = 'Left'
DataRepresentation5.DiffuseColor = [1.0, 1.0, 1.0]
DataRepresentation5.SelectionCellLabelOpacity = 1.0
DataRepresentation5.Source = "Arrow"
DataRepresentation5.Source.Invert = 0
DataRepresentation5.Masking = 0
DataRepresentation5.Opacity = 1.0
DataRepresentation5.LineWidth = 1.0
DataRepresentation5.MeshVisibility = 0
DataRepresentation5.Visibility = 1
DataRepresentation5.SelectionCellLabelFontSize = 18
DataRepresentation5.CubeAxesCornerOffset = 0.0
DataRepresentation5.SelectionPointLabelJustification = 'Left'
DataRepresentation5.SelectionPointLabelVisibility = 0
DataRepresentation5.SelectOrientationVectors = ''
DataRepresentation5.CubeAxesTickLocation = 'Inside'
DataRepresentation5.CubeAxesXAxisMinorTickVisibility = 1
DataRepresentation5.CubeAxesYAxisVisibility = 1
DataRepresentation5.SelectionPointLabelFontFamily = 'Arial'
DataRepresentation5.Source.ShaftResolution = 6
DataRepresentation5.CubeAxesFlyMode = 'Closest Triad'
DataRepresentation5.SelectScaleArray = ''
DataRepresentation5.CubeAxesYTitle = 'Y-Axis'
DataRepresentation5.ColorAttributeType = 'POINT_DATA'
DataRepresentation5.SpecularPower = 100.0
DataRepresentation5.Texture = []
DataRepresentation5.SelectionCellLabelShadow = 0
DataRepresentation5.AmbientColor = [1.0, 1.0, 1.0]
DataRepresentation5.MapScalars = 0
DataRepresentation5.PointSize = 2.0
DataRepresentation5.Source.TipLength = 0.35
DataRepresentation5.SelectionCellLabelFormat = ''
DataRepresentation5.Scaling = 0
DataRepresentation5.StaticMode = 0
DataRepresentation5.SelectionCellLabelColor = [0.0, 1.0, 0.0]
DataRepresentation5.Source.TipRadius = 0.1
DataRepresentation5.EdgeColor = [0.0, 0.0, 0.5000076295109483]
DataRepresentation5.CubeAxesXAxisTickVisibility = 1
DataRepresentation5.SelectionCellLabelVisibility = 0
DataRepresentation5.NonlinearSubdivisionLevel = 1
DataRepresentation5.CubeAxesXAxisRange = [0.0, 1.0]
DataRepresentation5.Representation = 'Surface'
DataRepresentation5.CubeAxesYAxisRange = [0.0, 1.0]
DataRepresentation5.CustomBounds = [0.0, 1.0, 0.0, 1.0, 0.0, 1.0]
DataRepresentation5.Orientation = [0.0, 0.0, 0.0]
DataRepresentation5.CubeAxesEnableCustomAxisRange = 0
DataRepresentation5.CubeAxesXTitle = 'X-Axis'
DataRepresentation5.CubeAxesInertia = 1
DataRepresentation5.BackfaceOpacity = 1.0
DataRepresentation5.SelectionCellFieldDataArrayName = 'vtkOriginalCellIds'
DataRepresentation5.SelectionColor = [1.0, 0.0, 1.0]
DataRepresentation5.Ambient = 0.0
DataRepresentation5.SelectionPointLabelFontSize = 18
DataRepresentation5.ScaleFactor = 303.2400146484375
DataRepresentation5.BackfaceAmbientColor = [1.0, 1.0, 1.0]
DataRepresentation5.Source.ShaftRadius = 0.03
DataRepresentation5.SelectMaskArray = ''
DataRepresentation5.SelectionLineWidth = 2.0
DataRepresentation5.CubeAxesZAxisMinorTickVisibility = 1
DataRepresentation5.CubeAxesXAxisVisibility = 1
DataRepresentation5.Interpolation = 'Gouraud'
DataRepresentation5.SelectionCellLabelFontFamily = 'Arial'
DataRepresentation5.SelectionCellLabelItalic = 0
DataRepresentation5.CubeAxesYAxisMinorTickVisibility = 1
DataRepresentation5.CubeAxesZGridLines = 0
DataRepresentation5.SelectionPointLabelFormat = ''
DataRepresentation5.SelectionPointLabelOpacity = 1.0
DataRepresentation5.BackfaceDiffuseColor = [1.0, 1.0, 1.0]
DataRepresentation5.Pickable = 1
DataRepresentation5.CustomBoundsActive = [0, 0, 0]
DataRepresentation5.SelectionRepresentation = 'Wireframe'
DataRepresentation5.SelectionPointLabelBold = 0
DataRepresentation5.ColorArrayName = 'MetaImage'
DataRepresentation5.SelectionPointLabelItalic = 0
DataRepresentation5.AllowSpecularHighlightingWithScalarColoring = 0
DataRepresentation5.SpecularColor = [1.0, 1.0, 1.0]
DataRepresentation5.LookupTable = a3_MetaImage_PVLookupTable
DataRepresentation5.SelectionPointSize = 5.0
DataRepresentation5.SelectionCellLabelBold = 0
DataRepresentation5.Orient = 0
Render()
# save figures
WriteImage("/Users/matt/Documents/DPhil/written_work/thesis/Ch8/Figs/structure_tensor_glyphs.png" )
